import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CartContextProvider from "@/context/CartContextProvider";
import WishlistContextProvider from "@/context/WishlistContextProvider";
import AuthProvider from "@/context/AuthProvider";
import UserContextProvider from "@/context/UserContextProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} h-full w-full`}>
        <WishlistContextProvider>
          <Header />
          <CartContextProvider>
            <AuthProvider>
              <UserContextProvider>
                <Navbar />
                {children}
              </UserContextProvider>
            </AuthProvider>
          </CartContextProvider>
          <Footer />
        </WishlistContextProvider>
      </body>
    </html>
  );
}
